### ISSUE TITLE
未找到未配准的SMOD数据集

### ISSUE THREAD

**Issue by LemonGauss** [bigD233/AMFD#2]
未找到未配准的SMOD数据集，只找到配准过的SMOD数据集，能否提供链接

**Comment by bigD233** [comment]
I have updated the uncalibrated data on kaggle, in the folder "raw" (the link is the same as in the paper), and due to the different recording methods, there are only uncalibrated images for the night.

**Comment by LemonGauss** [comment]
Are there any annotations for unaligned image pairs?

**Comment by bigD233** [comment]
> Are there any annotations for unaligned image pairs?

Sorry, we did not annotate the unaligned image pairs.
